### PR TITLE
Replace Dry and RecursiveOpenStruct with K8s::HashStruct + K8s::Type

### PR DESCRIPTION
**Pull request by kke**
Closes #128 (included, merging that will simplify this diff)
Closes #125 (included, merging that will simplify this diff)
Closes #112 
Closes #123 

Related to #121 

Replace RecursiveOpenStruct, Dry::Struct and Dry::Types with a simple `K8s::HashStruct` and `K8s::Type`, thus dropping the dependencies.

### CODE REVIEW

**Comment by kke** [comment]
wip: Specs pass, but I'm a bit skeptical if it actually really works.

**Comment by kke** [comment]
Surprisingly `pharos up` passes with this (if you add the recursive-open-struct dependency to pharos),

**Comment by kke** [comment]
The Type stuff is not needed if the api/metav1 -stuff is treated like any random resource and the predefined structs are removed, but that will require changing a lot of the specs.

**Comment by pre** [comment]
I tested and found that there are issues with this branch.

Eg. the following code throws `undefined method `resourceVersion' for nil:NilClass (NoMethodError)`:

```ruby
# simplified copy-paste from production code
resources = K8s::Client.in_cluster_config
  .api('my_api')
  .resource('lolcats', namespace: 'copypasted')
  
checkpoint = resources.meta_list.metadata.resourceVersion
resources.watch(timeout: 900, resourceVersion: checkpoint) do |event|
  # ... 
end
```

Same code with k8s-client 0.10.1 works /  has been working for months with older versions.

**Comment by kke** [comment]
Starting to thing the `K8s::HashStruct` and `K8s::Type` add too much complication, maybe better to just use the RecursiveOpenStruct for everything eventhough it is mutable.

**Comment by kke** [comment]
Replaced by #147

**Comment by kke** [comment]
@pre You can try with #147

**Pull request closed without merging**
