### PR TITLE
Fix path prefix handling in server address

### LINKED ISSUE #157: Server addresses with path-prefix do not work
As discussed in #110 - there seems to be some sort of bug in the path prefix handling.

The path is in the request twice.

```
client.api('v1').resource('ingresses', namespace: 'default').list()
```

Tries to make a request to:

```
/k8s/clusters/c-blahblah/k8s/clusters/c-blahblah/api/v1
```

And receives `NotFound`.

### PR DESCRIPTION
**Pull request by kke**
Fixes #157 
See #110

### CODE REVIEW

**Comment by rbq** [comment]
Yay! I can verify that with this workaround it runs with Rancher!

I assume it breaks using a path (prefix) like `/api/api` though?

**Comment by kke** [comment]
Yep, that's why that check was left out originally. I still don't understand why it gets added twice, and I have not been able to reproduce the problem in the console.

**Comment by kke** [comment]
Included in [0.10.3](https://github.com/kontena/k8s-client/releases/tag/v0.10.3) (https://rubygems.org/gems/k8s-client/versions/0.10.3)

**Comment by rbq** [comment]
Yeah, I tried to understand what's going on but quickly gave up. In `K8s::Transport` everything seemed fine; when sending a request it builds the path with prefix.

But for some reason `K8s::APIClient` also reaches into `K8s::Transport`, adding the prefix a second time?

```ruby
def path(*path)
  @transport.path(self.class.path(@api_version), *path)
end
```

So I tried to change that to just:

```ruby
def path(*path)
  File.join self.class.path(@api_version), *path
end
```

The result seemed to be one request with a correct URL (not sure what's going on there, discovering available APIs or something?)—immediately followed by an exception with a path that was now missing the prefix. 🤯

**Comment by rbq** [comment]
Anyway, thanks a lot! I'll now try building a little Sinatra app listing all the Ingresses deployed on our cluster. :)

**Pull request merged**
